spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sales-board
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080  
  servlet:
    context-path: /sb

jwt:
  secret: Y5ofTi8RXIfdOogL3_qcBx96fDSs2VyiLZLbiUa_j90=
  expiration-ms: 86400000
